---
# play1

- hosts: node-one 
  remote_user: root
  tasks:
    - name: crear un usuario en cada nodo con la informacion dada
      user: name=admin password=123 group=user home=/users/admin

- hosts: node-two 
  remote_user: root
  tasks:
    - name: crear un usuario en cada nodo con la informacion dada
      user: name=dev password=123 group=user home=/users/dev



- hosts: servidorweb
  roles:
    - role: webweb

# play2

- hosts: all
  tasks:
    - include: play2.yml
    
   

...